name: Deploy SINIM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Build SINIM
        run: npm run build

      - name: Install OpenVPN client
        run: |
          sudo apt-get update
          sudo apt-get install -y openvpn

      - name: Create VPN credentials file
        run: |
          echo "randy.frias" > vpn-credentials
          echo "Kevin14080100." >> vpn-credentials

      - name: Connect to VPN
        run: sudo openvpn --config vpn-config.ovpn --auth-user-pass vpn-credentials --daemon

      - name: Wait for VPN to connect
        run: sleep 10

      - name: Ping server
        run: ping -c 5 192.168.0.81

      - name: Transfer files to remote server
        uses: appleboy/scp-action@master
        with:
          host: "192.168.0.81"
          username: "randyfrias"
          password: "Kevin14080100."
          source: "${{ github.workspace }}/.next/"
          target: "/var/www/SINIM"
        env:
          INPUT_TIMEOUT: 180

      - name: Disconnect from VPN
        run: sudo killall openvpn
