name: Deploy SINIM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Build SINIM
        run: npm run build

      - name: Package files for transfer
        run: tar -czvf /tmp/my_files.tar.gz -C "${{ github.workspace }}/out"

      - name: Transfer files to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }} # Set this secret in your GitHub repository settings
          username: ${{ secrets.SERVER_USERNAME }} # Set this secret in your GitHub repository settings
          password: ${{ secrets.SERVER_PASSWORD }} # Set this secret in your GitHub repository settings
          source: "/tmp/my_files.tar.gz"
          target: "/var/www/SINIM" # Replace with the appropriate target directory on your server

