name: Deploy to Remote Server
on:
  push:
    branches:
      - main # Cambiar esto al nombre de la rama que quieres que despliegue el proyecto

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: 190.167.210.22
          port: 5555
          username: randyfrias
          password: Kevin14080100.
          script: |
            # Comandos a ejecutar en el servidor remoto
            pkill -9 -f "node.*3000"
            cd /var/www/SINIM
            git pull
            npm install
            npm run build
            npm run start
