name: Deploy SINIM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Build SINIM
        run: npm run build

      - name: Transfer files to remote server
        uses: appleboy/scp-action@master
        with:
          host: "190.167.210.22" # Set this secret in your GitHub repository settings
          port: 5555 # Set this secret in your GitHub repository settings
          username: "randyfrias" # Set this secret in your GitHub repository settings
          password: "Kevin14080100." # Set this secret in your GitHub repository settings
          source: "${{ github.workspace }}/.next/"
          target: "/var/www/SINIM" # Replace with the appropriate target directory on your server
        env:
          INPUT_TIMEOUT: 180
