name: Deploy SINIM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Build SINIM
        run: npm run build

      - name: Transfer files to remote server
        run: |
          $session = New-PSSession -ComputerName $env:SERVER_IP -Credential (New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $env:SERVER_USERNAME, (ConvertTo-SecureString -String $env:SERVER_PASSWORD -AsPlainText -Force))
          Copy-Item -Path "${{ github.workspace }}/out/*" -Destination 'E:\PLATAFORMAS WEB\SINIM' -ToSession $session
          Remove-PSSession -Session $session
